openapi: 3.0.0
info:
  version: 0.0.1
  title: serverless-stack-name
x-api-gateway-name: api-gateway-restapi-name
x-api-hystrix-dashboard: false
paths:
  '/pets':
    x-micro-service-name: micro-service-for-pets
    get:
      tags:
        - Pets Service Group
      description: 'Get Pets Information'
      operationId: getPets
      responses:
        '200':
          description: Success
    post:
      tags:
        - Pets Service Group
      description: 'Create Pets Information'
      operationId: createPet
      responses:
        '200':
          description: Success
  '/pets/{id}':
    x-micro-service-name: micro-service-for-pets
    x-micro-service-model-name: people-pets
    x-micro-service-hystrix-stream: true
    put:
      x-micro-service-circuit-protection: true
      x-micro-service-circuit-timeout: 60000
      x-micro-service-circuit-duration: 30000
      x-micro-service-circuit-threshold: 0.1
      tags:
        - Pets Service Group
      description: 'Update Pets Information'
      parameters:
      - in: path
        name: id
        required: true
        schema:
            type: string
      operationId: updatePetById
      responses:
        '200':
          description: Success
    post:
      tags:
        - Pets Service Group
      description: 'Create Pets Information By Id'
      operationId: linkPetToPerson
      parameters:
      - in: path
        name: id
        required: true
        schema:
            type: string
      - in: query
        name: filter        
        schema:
            type: string    
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                foo:
                  type: string
      responses:
        '200':
          description: Success
  '/people':
    x-micro-service-name: micro-service-for-people
    x-micro-service-model-name: people-pets
    get:
      tags:
        - People Service Group
      description: 'Get People Information'
      operationId: getPeople
      responses:
        '200':
          description: Success
    put:
      tags:
        - People Service Group
      description: 'Update People Information'
      operationId: putPeople
      responses:
        '200':
          description: Success
    post:
      tags:
        - People Service Group
      description: 'Create People Information By Id'
      operationId: createPeople
      responses:
        '200':
          description: Success
servers:
  - url: /