openapi: 3.0.0
info:
  version: 0.0.1
  title: serverless-stack-name
x-api-gateway-name: api-gateway-restapi-name
paths:
  '/pets':
    x-lambda-service-name: lambda-function-name-for-pets
    x-swagger-router-controller: routerControllerNameForPets
    get:
      tags:
        - Pets Service Group
      description: 'Get Pets Information'
      operationId: getPets
      responses:
        '200':
          description: Success
  '/people':
    x-lambda-service-name: lambda-function-name-for-people
    x-swagger-router-controller: routerControllerNameForPeople
    get:
      tags:
        - People Service Group
      description: 'Get People Information'
      operationId: getPeople
      responses:
        '200':
          description: Success
servers:
  - url: /