openapi: 3.0.0
info:
  version: 0.0.1
  title: serverless-stack-name
x-api-gateway-name: api-gateway-restapi-name
x-api-hystrix-dashboard: false
paths:
  '/pets':
    x-micro-service-name: micro-service-for-pets
    get:
      x-micro-service-model-list-objects: aws-s3
      x-micro-service-model-list-objects-from: category
      tags:
        - Pets Service Group
      description: 'Get Pets Information'
      operationId: getPets
      parameters:
      - name: category
        in: query        
        schema:
          type: string
        required: true
      - name: cats
        in: query        
        schema:
          type: string
        required: false
      responses:
        '200':
          description: Success
    post:
      x-micro-service-model-create-object: aws-s3
      x-micro-service-model-create-object-name: bucketName
      x-micro-service-model-create-object-data: dataObject
      tags:
        - Pets Service Group
      description: 'Create Pets Information'
      operationId: createPet
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bucketName:
                  type: string
                dataObject:
                  type: object
      responses:
        '200':
          description: Success
    put:
      x-micro-service-model-update-object: aws-s3
      x-micro-service-model-update-object-name: bucketName
      x-micro-service-model-update-object-data: dataObject
      x-micro-service-model-update-object-fields: ['foo', 'test']       
      tags:
        - Pets Service Group
      description: 'Update Pets Information'
      operationId: updatePetWithFields
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bucketName:
                  type: string
                dataObject:
                  type: object
      responses:
        '200':
          description: Success
  '/pets/{id}':
    x-micro-service-name: micro-service-for-pets
    x-micro-service-model-name: people-pets
    x-micro-service-hystrix-stream: true    
    post:
      x-micro-service-circuit-protection: true
      x-micro-service-circuit-timeout: 60000
      x-micro-service-circuit-duration: 30000
      x-micro-service-circuit-threshold: 0.1
      tags:
        - Pets Service Group
      description: 'Create Pets Information By Id'
      operationId: linkPetToPerson
      parameters:
      - in: path
        name: id
        required: true
        schema:
            type: string
      - in: query
        name: filter        
        schema:
            type: string    
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                foo:
                  type: string
      responses:
        '200':
          description: Success
  '/people':
    x-micro-service-name: micro-service-for-people
    x-micro-service-model-name: people-pets
    get:
      x-micro-service-model-get-object: aws-s3
      x-micro-service-model-get-object-name: bucketName      
      x-micro-service-model-get-object-fields: ['foo', 'test']
      tags:
        - People Service Group
      description: 'Get People Information'
      operationId: getPeople
      parameters:
      - in: query
        name: bucketName        
        schema:
            type: string
        required: true
      responses:
        '200':
          description: Success
    put:
      tags:
        - People Service Group
      description: 'Update People Information'
      operationId: putPeople
      responses:
        '200':
          description: Success
    post:
      tags:
        - People Service Group
      description: 'Create People Information By Id'
      operationId: createPeople
      responses:
        '200':
          description: Success
servers:
  - url: /